### ISSUE TITLE
[Python] Can we add the ability to save model parameters to a Booster object?

### ISSUE THREAD

**Issue by bbennett36** [lightgbm-org/LightGBM#1364]
One of the biggest features that I think LightGBM is missing is having the ability to retrieve parameters from a trained model.  
  
When I first started using LightGBM I got burned a couple times because I thought the model was using certain parameters but it actually wasn't due to a small type in the parameter name or using an incorrect alias so I think this will greatly benefit newcomers. Even after working with LightGBM for months I still run into issues where I change a parameter setting but never actually run the model again and then I think it's using a parameter when it's really not. This is something that always worries me with models that I'm putting into production because it's really easy to mess up and no way to really verify which parameters the model is actually using. 
  
Maybe just add a parameter called 'save_params'(something alone those lines) to give the option to save the parameters or not.  
  
Then when this parameter is set to True, we save the params to the trained Booster object. I think it should save ALL parameters. If it was set by the user, then return those values. If they were not set by the user then return all default parameter values. This way when we are using LightGBM we will be able to verify default values for all parameters. This should help keeping documentation up to date as well. There are some old resources out there that have the wrong default values for certain parameters which can and will cause confusion for people in the future.  
  
This seems like a pretty easy feature to add and I don't really see any problems that could arise from this, I would give it a shot but I don't know how to implement this in the C code.  
  
What are your thoughts on this?

**Comment by guolinke** [comment]
@bbennett36 thanks, that is a good request. I will do it when i am free.

**Comment by guolinke** [comment]
Now the parameters will be auto saved in the end of model file.

**Comment by bbennett36** [comment]
@guolinke You guys are awesome! Thanks!

**Comment by jdanbrown** [comment]
It looks like these params aren't read back in in `LoadModelFromString`. Is that intended? I've run into two unexpected issues so far caused by that (in python):
- `gbm.save_model(...)` does include the params, as expected, but `pickle.loads(pickle.dumps(gbm)).save_model(...)` doesn't include the params, I think because `LoadModelFromString` doesn't read them back in after `SaveModelToString` writes them out.
- `lgb.train(keep_training_booster=True, ...).save_model(...)` does include the params, but the default `lgb.train(keep_training_booster=False, ...).save_model(...)` doesn't include the params, I think also because of `LoadModelFromString`.

Including these is very helpful. Thanks for adding them!

**Comment by acmilannesta** [comment]
Could I also specify `keep_training_booster = True` in `lgbm.cv` function?

**Comment by jameslamb** [comment]
I'm going to lock conversation on this old thread, to keep the conversation focused.

@acmilannesta I've replied to your question on the new issue you created, #4883.

For anyone else arriving here from search engines, please open a new issue with a new question related to this if you have one.
